triggers:
  flow-listener-1:
    name: Flow Listener
    parameters:
      id: Fruit
    enabled: true
    invoke:
      flow: 01invokeFlow
      parameters:
        request: $.request
        config: $.config
        env: $.env
