var APIBuilder = require('@axway/api-builder-runtime');
var Model = APIBuilder.createModel('customerOrder', {
    "connector": "composite",
    "fields": {
        "customerName": {
            "type": "string",
            "model": "mysql/customers",
            "name": "customerName"
        },
        "contactLastName": {
            "type": "string",
            "model": "mysql/customers",
            "name": "contactLastName"
        },
        "contactFirstName": {
            "type": "string",
            "model": "mysql/customers",
            "name": "contactFirstName"
        },
        "city": {
            "type": "string",
            "model": "mysql/customers",
            "name": "city"
        },
        "mysql/orders": {
            "model": "mysql/orders",
            "type": "array"
        }
    },
    "actions": [
        "read"
    ],
    "metadata": {
        "primarykey": "customerNumber",
        "primaryKeyDetails": {
            "autogenerated": false,
            "type": "number"
        },
        "inner_join": [
            {
                "model": "mysql/orders",
                "join_properties": {
                    "customerNumber": "customerNumber"
                }
            }
        ]
    }
});
module.exports = Model;